# Generated by Django 4.2.5 on 2024-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
